### ISSUE TITLE
PGC - Per Game Configurations doesn't work anymore in the latest beta build

### ISSUE THREAD

**Issue by Emulatorer** [reicast/gamedb#127]
I open all of my dreamcast game to add it to PGC but it doesn't show any one of them also everytime I open the game it's always ask for the date/month/year even if I already settings :/ this issue doesn't happen in the previous build I don't know exactly what build version of it 🤔

### screenshot
![screenshot_2019-02-19-22-35-34](https://user-images.githubusercontent.com/37603562/53023180-aa194680-3497-11e9-8941-397c592555a8.png)
### phone specs
Mali-450 GPU
Android 5.1 lollipop
2gb ram & 16gb rom

*sorry for my english and hoping you will fixed this issue before the released of the stable version in google playstore

**Comment by Emulatorer** [comment]
@skmp can I close this ?

**Comment by baka0815** [comment]
@Emulatorer  It's your issue. :-)
If this is fixed and no longer a problem on your end, you're free to close it.

**Comment by Emulatorer** [comment]
Ok hoping my remaining issue will be fixed someday
https://github.com/reicast/reicast-emulator/issues/1546
