### ISSUE TITLE
Ninja Assault borked Controls

### ISSUE THREAD

**Issue by eckso** [reicast/gamedb#129]
So specially in this title (others seems fine but didn't test enough) TRIGGER control doesn't respond.
There are like 4 Input Descriptions, START, ENTER, COIN, TRIGGER, (aside from the sticks and dpad), the trigger button doesn't do anything.

Also for some reason, player 2 Input Descriptions are mapped to Input Device 1 buttons by default.
Running latest build and core on PC with wireless X360 controller.

edit: I just realized this is the upstream reicast emulator, should post on libretro I guess.

**Comment by flyinghead** [comment]
Yes, here is the right place for this issue: https://github.com/libretro/reicast-emulator/issues
