### ISSUE TITLE
New Reicast db website

### ISSUE THREAD

**Issue by djleven** [reicast/gamedb#131]
A data-driven, reactive (Vuejs based) SPA for the Reicast db website. The site incorporates the existing test report google forms and game data from [IGDB](https://www.igdb.com). The SPA routes are [prerendered](https://github.com/chrisvfritz/prerender-spa-plugin) for SEO purposes in production.
Aside from the website, the codebase is built on top of the [Quasar framework](https://github.com/quasarframework/quasar) easily allowing us to make builds targeting mobile (via Cordova) and desktop (via Electron) platforms (+ different architectures). The docker environments configured for building Android, Windows and Linux executables will be provided in the repository.

[Live preview](https://reicas.ttic.ca)

![landing](https://user-images.githubusercontent.com/11492131/59765238-a215bb80-926b-11e9-8f50-31af9d51fd91.png)
![gamelist](https://user-images.githubusercontent.com/11492131/59765245-a6da6f80-926b-11e9-8835-bbb143a51a19.png)
![gamelist-2](https://user-images.githubusercontent.com/11492131/59765249-a8a43300-926b-11e9-8832-b29e64ad50a9.png)
![game-overview](https://user-images.githubusercontent.com/11492131/59765253-aa6df680-926b-11e9-8874-2a56e4a24837.png)
![game_info](https://user-images.githubusercontent.com/11492131/59765266-b5288b80-926b-11e9-8cd2-ed89349411c3.png)
![game-shots](https://user-images.githubusercontent.com/11492131/59765272-b8237c00-926b-11e9-996a-5ba9e96a300b.png)
![game-tests](https://user-images.githubusercontent.com/11492131/59765279-bb1e6c80-926b-11e9-97ca-9bf9aeaee7cc.png)
![game-test-videos](https://user-images.githubusercontent.com/11492131/59765281-bce83000-926b-11e9-8538-f7751c51160d.png)

**Comment by skmp** [comment]
@reicast/members @reicast/testers Can we have some feedback on this? I'm loving it so far.

**Comment by skmp** [comment]
Also, @FernandoBasso!

**Comment by djleven** [comment]
@skmp Would it not be better to have separate repositories for the gamedb website and for the game issues per se? How about we dedicate the current repository for the issues and create a new one for the web/app?

**Comment by FernandoBasso** [comment]
@skmp I would definitely go for it! Looks amazing!

@djleven Superb job! Congrats are in order!

**Comment by djleven** [comment]
@FernandoBasso Thank you :)

**Comment by spielvan** [comment]
@djleven My congratulations, it was great this db
