### ISSUE TITLE
The King Of Fighters Evolution Touch Screen Controller Missing/Unavailable [$100]

### ISSUE THREAD

**Issue by Emulatorer** [reicast/gamedb#4]
As you see in this Video https://youtu.be/z3t533fnd2A The Touch Screen Controller is Missing After the intro of Dreamcast Logo and the only left is analog which is become large and no use.

**Comment by Emulatorer** [comment]
Phone Specs:

Android 5.1
Mali-450 Mp GPU
Octacore
1.4GHz CPU
2GB RAM

reicast r7 beta [02901d6]

**Comment by skmp** [comment]
Is this http://gamedb.reicast.com/games/king-of-fighters-evolution or http://gamedb.reicast.com/games/king-of-fighters-99-evolution ?
