### ISSUE TITLE
ecco the dolphin: serious grafx  problems.

### ISSUE THREAD

**Issue by skmp** [reicast/gamedb#42]
_From @1seam1 on May 8, 2017 4:56_

it only seems to render the polygons closest to ecco. wondering if its a fog issue? i have no idea.  

as seen here

https://youtu.be/2yjzTmCsoog?t=266

**Comment by skmp** [comment]
This is probably missing fog. @reicast/testers can this be moved to the reicast/gamedb#2 tracker?

**Comment by baka0815** [comment]
Since https://github.com/reicast/reicast-emulator/pull/1449 got merged, this is fixed.
