### ISSUE TITLE
Street Fighter Alpha 3 black screen

### ISSUE THREAD

**Issue by skmp** [reicast/gamedb#49]
_From @fivefeet8 on May 8, 2015 16:49_

Game:  Street Fighter Alpha 3 (US)  ver.1001

The game is in GDI format as below:

file.gdi
track01.bin
track02.raw
track03.bin

The game loads the Dreamcast logo then goes to a black screen.  Device is still functional, but it stays at the black screen.  I'm guessing it should be loading the Capcom intro logo, but it doesn't.  I can still exit the application like normal by bringing up the menu.

Device:  Nvidia Shield Tablet (Lollipop)
Commit Vers: 86004e687960e7aeac0af812d111d45f9932a4bc

I've tried the game on various versions in the past and none have worked as well.

**Comment by skmp** [comment]
_From @MrPsyMan on May 21, 2015 15:56_

If I recall correctly that's a timing issue with DMAs. Will take a while until fixed.

**Comment by skmp** [comment]
_From @twinaphex on October 17, 2016 1:23_

I added a hack for this in libretro-reicast, it at least works there fine.

**Comment by skmp** [comment]
_From @sabula310 on October 17, 2016 5:42_

cool

**Comment by skmp** [comment]
_From @sabula310 on October 17, 2016 5:43_

how did you do it

**Comment by skmp** [comment]
_From @twinaphex on October 17, 2016 15:42_

By implementing a hack which both MrPsyMan and skmp seems to be against, so have fun waiting until 2020 (or 2030) before some magical reversing has happened to fix this.

Until then, you can just use libretro-reicast instead.

**Comment by AbandonedCart** [comment]
Fixed by https://github.com/reicast/reicast-emulator/pull/1315
