### ISSUE TITLE
Propeller Arena, black sky

### ISSUE THREAD

**Issue by skmp** [reicast/gamedb#50]
_From @dayara on April 12, 2015 23:17_

Screenshot: https://www.dropbox.com/l/NFS02xi2S9i00hHjWsBmPp

Log: http://loungekatt.no-ip.biz:3194/ReicastBot/report/logs/1428880225221.txt

_Copied from original issue: reicast/reicast-emulator#636_

**Comment by skmp** [comment]
@dayara can you re-test this with current master?

**Comment by skmp** [comment]
_From @dayara on April 13, 2018 4:5_

Not yet.

**Comment by dayara** [comment]
Now it works. : )
